### ISSUE TITLE
linkify links exporting to html

### ISSUE THREAD

**Issue by StevenIseki** [vacenz/last-draft#10]
@codeKonami I just put in a small update to the logic for linkify [here](https://github.com/vacenz/last-draft/commit/b26effc1a7ced7740eb0229f8b32cdd4f07a7b39) which means that links are only matched when they have a url schema.

This now works well in my editor I am using last draft for, but I think that is because on the server we are transforming valid links to an `<a>` tag. It looks like there is [no entity support](https://github.com/sstur/draft-js-export-html/issues/21) for draft-js-export-html so I am not sure what the best approach for this is? Using [draft-convert](https://github.com/HubSpot/draft-convert) convertToHTML would work well for this, but I have found it to be very slow compared to draft-js-export-html.

The other update was to links in the toolbar, ensuring they save with the schema. It fixes the issue where it was saving invalid links e.g. `g.co` where we really want to save `https://g.co`

**Comment by codeKonami** [comment]
I let you have a look at the PR... it's more a hack than a proper solution. But since there is no entity support for draft-js-export-html at least this is an alternative.
