### ISSUE TITLE
Mismatch between git repo & npm package

### ISSUE THREAD

**Issue by s123121** [vacenz/last-draft#12]
Hello, thanks for the great editor.
I try to integrate your editor into my project. However, the package failed to build.
The error is: 
`Module not found: Error: Cannot resolve 'file' or 'directory' ./Blockquote in /node_modules/last-draft/lib/components/Buttons`
However, in the npm(yarn) package, inside the above folder, there is this file:
`BlockQuote.js`
as in your git repo:
`Blockquote.js`
(Notice the capitalized Q, this only fail to build on Linux, it is working fine in mac)

**Comment by StevenIseki** [comment]
Hi @s123121 Thanks a lot for pointing out this issue. 
I think I have fixed the problem, as you mentioned renaming `Blockquote` to `BlockQuote`. Let me know how it goes now on linux. Thanks and feel free to star if you like the Editor.
