### ISSUE TITLE
Plugins Clarification

### ISSUE THREAD

**Issue by levbrie** [vacenz/last-draft#14]
I see you've created your own custom plugins as examples - does this mean that *last-draft* won't work with [draft-js-plugins](https://github.com/draft-js-plugins/draft-js-plugins)?  If not, could you give some clarification as to why and what kind of work needs to be done to either modify such plugins or create our own?  If they are meant to work with *last-draft* out of the box, perhaps it would be a good thing to mention in the documentation - that would be a big selling point I think.

**Comment by StevenIseki** [comment]
It is an interesting question, At this stage Draft.js plugins only work with the Draft.js Plugin Editor so in a sense they are just as locked down to a particular Editor as Last-Draft and Megadraft plugins are. Last Draft is an extension of Megadraft's plugin approach so any Megadraft plugins should work well with Last Draft, possibly with some small tweaking needed. 

As far as getting Draft.js plugins to work with Last Draft, it is a pretty different approach and I would say its unlikely. However any of the Draft.js plugins should be able to be ported over easily enough. At the moment the main ones missing in Last Draft are Mentions plugin, Sticker plugin as well as improving the Emoji plugin. I am planning on work on these plugins over the next month.

**Comment by levbrie** [comment]
Hey @StevenIseki that's really too bad.  There's way too much duplication of work going on in the Draft.js ecosystem right now.  Given that `last-draft` is one of the only projects that seems to be really active right now, perhaps you should propose a standard plugin system based on the way you're doing it - seems like it would help you get more plugins from the community and help the community so that each new draft.js editor wouldn't have to design its own plugin system.

**Comment by ricobl** [comment]
Hey @levbrie! I agree that there's too much duplication.

On Megadraft's side, there's intention on integrating with draft-js-plugins: https://github.com/globocom/megadraft/issues/141

Maybe last-draft could follow the same approach.

**Comment by StevenIseki** [comment]
Interesting @ricobl I was looking to make all of the last draft plugins compatible with Megadraft in the coming weeks, which at this stage would mean having seperate but similar Megadraft plugins e.g. for Emoji, Mention, Sticker and Color Picker. 

That would be some great work to make the MegaDraft Editor a plugin itself, in a sense a replacement for the Draft-js-plugin Editor. If this is feasible I would definitely either follow with Last Draft, or push all of the Last Draft plugins over to MegaDraft. Possibly adding the html conversion plugin which would take care of html export and import which is the main feature of Last Draft other than the plugins.

**Comment by svnm** [comment]
I think this is all cleared up now. 
v2 is the Megadraft inspired version with `ld` plugins
v3 uses draft-js-plugins including the custom [last-draft-js-plugins](https://github.com/vacenz/last-draft-js-plugins) for toolbar, modals and sidebar.
