### ISSUE TITLE
Enable multiple headings

### ISSUE THREAD

**Issue by levbrie** [vacenz/last-draft#24]
Awesome job on last-draft! It's really great.  Would love it if it were possible to choose multiple headings in the blocks array, as opposed to just h2 - seems like the only interface to extending last-draft right now is through plugins, and that would probably be overkill for users who just want to include h1, h3, h4, h5, and/or h6 tags.

**Comment by StevenIseki** [comment]
@levbrie That makes sense, I will set that up in a few days. thanks.

**Comment by levbrie** [comment]
Awesome!

**Comment by StevenIseki** [comment]
This should be fixed now in version 1.3.5. The H1, H2, H3, H4, H5 icons are in but may need some tweaking if anyone has some design skills. I was just using SVG text. If you only have the 1 header it gets the H icon, which will make it consistent and makes sense. Also added the option to disable the separators in this version.
