### ISSUE TITLE
HTML editor not importing editorState on open 

### ISSUE THREAD

**Issue by kristajg** [vacenz/last-draft#25]
Steps to reproduce:

- include ld-html
- add to list of plugins
- have content in editor
- open HTML option in toolbar
- editorState content is not available

**Comment by StevenIseki** [comment]
Looks like a bug in the ld-html plugin due to the conversion of the text colors in the Editor, I will have a look into it tonight.

**Comment by StevenIseki** [comment]
Thanks for picking this issue up @kristajg 
It was some linting 'fixes' which caused the convert to be broken.
I have reverted that update to convert and all is fine now.
Should be working well now in version `1.4.0` and ld-html version `1.0.4`
Some nice updates to the modals went out in the latest version of `ld-html`, `ld-video` and `ld-audio` last night too which you should update to.

**Comment by kristajg** [comment]
@StevenIseki Thanks for looking into this so quickly, I appreciate it. Upgrading versions to try now.
