### ISSUE TITLE
Sidebar does not follow after uploading an image

### ISSUE THREAD

**Issue by codeKonami** [vacenz/last-draft#30]
You can see more clearly the bugs on the gif attached. There are two bugs.

First, after uploading an image, a block is created after the block image but the sidebar doesn't follow.

Secondly, after creating a new empty block, the sidebar comes down but a click on it doesn't display the toolbar at the right position it seems stuck on the block above the image. Some text needs to be entered to position correctly the toolbar.

![sidebar-bug](https://cloud.githubusercontent.com/assets/1849998/23361974/c2168f46-fcf3-11e6-9493-5654febeaa8e.gif)

**Comment by StevenIseki** [comment]
This is an issue in Draft.js any image uploading example. If you can find a draft.js Editor which does this another way, point me to it and I can take a look, but I think it needs a block before and after an atomic block.
