### ISSUE TITLE
why i m not able to run the project...

### ISSUE THREAD

**Issue by ChetnaSingh23** [vacenz/last-draft#35]
bundle.js:7779 Uncaught TypeError: Cannot read property '__reactInternalInstance$rc1tkywex4htm05izkv7h9f6r' of null(…)getClosestInstanceFromNode @ bundle.js:7779findParent @ bundle.js:126246handleTopLevelImpl @ bundle.js:126275perform @ bundle.js:27598batchedUpdates @ bundle.js:53331batchedUpdates @ bundle.js:9615dispatchEvent @ bundle.js:126355
http://localhost:3000/example/styles/plugins.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by StevenIseki** [comment]
I just tested a clean install, and no issues.
git clone https://github.com/vacenz/last-draft.git
cd last-draft
yarn install
npm run dev

All is fine. Can you give me a link to your repo. It sounds like maybe your port `3000` is already in use.

**Comment by ChetnaSingh23** [comment]
thanks Steven
I will try again
