### ISSUE TITLE
Can I decide which plugin to use in v3?

### ISSUE THREAD

**Issue by lext-7** [vacenz/last-draft#37]
Can I decide which plugin to use in v3?

I want to remove some plugins from default plugins that I don't need.

https://github.com/vacenz/last-draft/blob/v3/src/components/Editor.js#L146
https://github.com/vacenz/last-draft/blob/v3/src/components/Editor.js#L82

But as the code shows, it seems there is no way to add some custom plugins or enable/disable some plugins.

**Comment by StevenIseki** [comment]
I think it would be possible in v3 to pass in an array of the list of plugins as strings that you wanted to use. 

But the v3 of last draft is quite simple, just defining and initialising draft-js-plugins, it might be better to just copy the Editor `src` and the `package.json` plugin includes and use it in in your own project  in this way.

**Comment by StevenIseki** [comment]
Yes you can
Check out the https://github.com/vacenz/last-draft-example-v3
