### ISSUE TITLE
Two uploads at the same time is acting weird

### ISSUE THREAD

**Issue by codeKonami** [vacenz/last-draft#6]
Here is a gif of two uploads launched at the same time (each is waiting 10 seconds for completion)

![bug-last-draft](https://cloud.githubusercontent.com/assets/1849998/21711229/fe3dc27a-d3ed-11e6-976a-c49c8fd730bc.gif)

Once the first one is finished, the placeholder block of the second is destroyed. But once the promise is resolved the image block is created perfectly for the second image. However, the first image block seems to change to the placeholder type (you can notice the opacity modification)

**Comment by StevenIseki** [comment]
This is a bit strange, I will definitely have to look into a proper fix cleaning up the logic in uploading image blocks. As a temporary fix I might disable the upload of another image until the first is finished.

**Comment by StevenIseki** [comment]
For now I have prevented uploading 2 images at a time, so I will close this but I may enable it again once I refactor some of the logic with the related prs.
